/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the UnblockUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnblockUserResponse{}

// UnblockUserResponse struct for UnblockUserResponse
type UnblockUserResponse struct {
	// Duration of the request in human-readable format
	Duration string `json:"duration"`
	AdditionalProperties map[string]interface{}
}

type _UnblockUserResponse UnblockUserResponse

// NewUnblockUserResponse instantiates a new UnblockUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnblockUserResponse(duration string) *UnblockUserResponse {
	this := UnblockUserResponse{}
	this.Duration = duration
	return &this
}

// NewUnblockUserResponseWithDefaults instantiates a new UnblockUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnblockUserResponseWithDefaults() *UnblockUserResponse {
	this := UnblockUserResponse{}
	return &this
}

// GetDuration returns the Duration field value
func (o *UnblockUserResponse) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *UnblockUserResponse) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *UnblockUserResponse) SetDuration(v string) {
	o.Duration = v
}

func (o UnblockUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnblockUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UnblockUserResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnblockUserResponse := _UnblockUserResponse{}

	err = json.Unmarshal(data, &varUnblockUserResponse)

	if err != nil {
		return err
	}

	*o = UnblockUserResponse(varUnblockUserResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "duration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUnblockUserResponse struct {
	value *UnblockUserResponse
	isSet bool
}

func (v NullableUnblockUserResponse) Get() *UnblockUserResponse {
	return v.value
}

func (v *NullableUnblockUserResponse) Set(val *UnblockUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUnblockUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUnblockUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnblockUserResponse(val *UnblockUserResponse) *NullableUnblockUserResponse {
	return &NullableUnblockUserResponse{value: val, isSet: true}
}

func (v NullableUnblockUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnblockUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


