/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the BlockUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockUserResponse{}

// BlockUserResponse struct for BlockUserResponse
type BlockUserResponse struct {
	// Duration of the request in human-readable format
	Duration string `json:"duration"`
	AdditionalProperties map[string]interface{}
}

type _BlockUserResponse BlockUserResponse

// NewBlockUserResponse instantiates a new BlockUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockUserResponse(duration string) *BlockUserResponse {
	this := BlockUserResponse{}
	this.Duration = duration
	return &this
}

// NewBlockUserResponseWithDefaults instantiates a new BlockUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockUserResponseWithDefaults() *BlockUserResponse {
	this := BlockUserResponse{}
	return &this
}

// GetDuration returns the Duration field value
func (o *BlockUserResponse) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *BlockUserResponse) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *BlockUserResponse) SetDuration(v string) {
	o.Duration = v
}

func (o BlockUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BlockUserResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlockUserResponse := _BlockUserResponse{}

	err = json.Unmarshal(data, &varBlockUserResponse)

	if err != nil {
		return err
	}

	*o = BlockUserResponse(varBlockUserResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "duration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBlockUserResponse struct {
	value *BlockUserResponse
	isSet bool
}

func (v NullableBlockUserResponse) Get() *BlockUserResponse {
	return v.value
}

func (v *NullableBlockUserResponse) Set(val *BlockUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockUserResponse(val *BlockUserResponse) *NullableBlockUserResponse {
	return &NullableBlockUserResponse{value: val, isSet: true}
}

func (v NullableBlockUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


