/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the ListRecordingsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRecordingsResponse{}

// ListRecordingsResponse struct for ListRecordingsResponse
type ListRecordingsResponse struct {
	Duration string `json:"duration"`
	Recordings []CallRecording `json:"recordings"`
	AdditionalProperties map[string]interface{}
}

type _ListRecordingsResponse ListRecordingsResponse

// NewListRecordingsResponse instantiates a new ListRecordingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRecordingsResponse(duration string, recordings []CallRecording) *ListRecordingsResponse {
	this := ListRecordingsResponse{}
	this.Duration = duration
	this.Recordings = recordings
	return &this
}

// NewListRecordingsResponseWithDefaults instantiates a new ListRecordingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRecordingsResponseWithDefaults() *ListRecordingsResponse {
	this := ListRecordingsResponse{}
	return &this
}

// GetDuration returns the Duration field value
func (o *ListRecordingsResponse) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *ListRecordingsResponse) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *ListRecordingsResponse) SetDuration(v string) {
	o.Duration = v
}

// GetRecordings returns the Recordings field value
func (o *ListRecordingsResponse) GetRecordings() []CallRecording {
	if o == nil {
		var ret []CallRecording
		return ret
	}

	return o.Recordings
}

// GetRecordingsOk returns a tuple with the Recordings field value
// and a boolean to check if the value has been set.
func (o *ListRecordingsResponse) GetRecordingsOk() ([]CallRecording, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recordings, true
}

// SetRecordings sets field value
func (o *ListRecordingsResponse) SetRecordings(v []CallRecording) {
	o.Recordings = v
}

func (o ListRecordingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRecordingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration
	toSerialize["recordings"] = o.Recordings

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListRecordingsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration",
		"recordings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListRecordingsResponse := _ListRecordingsResponse{}

	err = json.Unmarshal(data, &varListRecordingsResponse)

	if err != nil {
		return err
	}

	*o = ListRecordingsResponse(varListRecordingsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "duration")
		delete(additionalProperties, "recordings")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListRecordingsResponse struct {
	value *ListRecordingsResponse
	isSet bool
}

func (v NullableListRecordingsResponse) Get() *ListRecordingsResponse {
	return v.value
}

func (v *NullableListRecordingsResponse) Set(val *ListRecordingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListRecordingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListRecordingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRecordingsResponse(val *ListRecordingsResponse) *NullableListRecordingsResponse {
	return &NullableListRecordingsResponse{value: val, isSet: true}
}

func (v NullableListRecordingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRecordingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


