/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the GetCallResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCallResponse{}

// GetCallResponse struct for GetCallResponse
type GetCallResponse struct {
	Call CallResponse `json:"call"`
	Duration string `json:"duration"`
	Members []MemberResponse `json:"members"`
	Membership *MemberResponse `json:"membership,omitempty"`
	OwnCapabilities []OwnCapability `json:"own_capabilities"`
	AdditionalProperties map[string]interface{}
}

type _GetCallResponse GetCallResponse

// NewGetCallResponse instantiates a new GetCallResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCallResponse(call CallResponse, duration string, members []MemberResponse, ownCapabilities []OwnCapability) *GetCallResponse {
	this := GetCallResponse{}
	this.Call = call
	this.Duration = duration
	this.Members = members
	this.OwnCapabilities = ownCapabilities
	return &this
}

// NewGetCallResponseWithDefaults instantiates a new GetCallResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCallResponseWithDefaults() *GetCallResponse {
	this := GetCallResponse{}
	return &this
}

// GetCall returns the Call field value
func (o *GetCallResponse) GetCall() CallResponse {
	if o == nil {
		var ret CallResponse
		return ret
	}

	return o.Call
}

// GetCallOk returns a tuple with the Call field value
// and a boolean to check if the value has been set.
func (o *GetCallResponse) GetCallOk() (*CallResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Call, true
}

// SetCall sets field value
func (o *GetCallResponse) SetCall(v CallResponse) {
	o.Call = v
}

// GetDuration returns the Duration field value
func (o *GetCallResponse) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *GetCallResponse) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *GetCallResponse) SetDuration(v string) {
	o.Duration = v
}

// GetMembers returns the Members field value
func (o *GetCallResponse) GetMembers() []MemberResponse {
	if o == nil {
		var ret []MemberResponse
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *GetCallResponse) GetMembersOk() ([]MemberResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *GetCallResponse) SetMembers(v []MemberResponse) {
	o.Members = v
}

// GetMembership returns the Membership field value if set, zero value otherwise.
func (o *GetCallResponse) GetMembership() MemberResponse {
	if o == nil || IsNil(o.Membership) {
		var ret MemberResponse
		return ret
	}
	return *o.Membership
}

// GetMembershipOk returns a tuple with the Membership field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCallResponse) GetMembershipOk() (*MemberResponse, bool) {
	if o == nil || IsNil(o.Membership) {
		return nil, false
	}
	return o.Membership, true
}

// HasMembership returns a boolean if a field has been set.
func (o *GetCallResponse) HasMembership() bool {
	if o != nil && !IsNil(o.Membership) {
		return true
	}

	return false
}

// SetMembership gets a reference to the given MemberResponse and assigns it to the Membership field.
func (o *GetCallResponse) SetMembership(v MemberResponse) {
	o.Membership = &v
}

// GetOwnCapabilities returns the OwnCapabilities field value
func (o *GetCallResponse) GetOwnCapabilities() []OwnCapability {
	if o == nil {
		var ret []OwnCapability
		return ret
	}

	return o.OwnCapabilities
}

// GetOwnCapabilitiesOk returns a tuple with the OwnCapabilities field value
// and a boolean to check if the value has been set.
func (o *GetCallResponse) GetOwnCapabilitiesOk() ([]OwnCapability, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnCapabilities, true
}

// SetOwnCapabilities sets field value
func (o *GetCallResponse) SetOwnCapabilities(v []OwnCapability) {
	o.OwnCapabilities = v
}

func (o GetCallResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCallResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["call"] = o.Call
	toSerialize["duration"] = o.Duration
	toSerialize["members"] = o.Members
	if !IsNil(o.Membership) {
		toSerialize["membership"] = o.Membership
	}
	toSerialize["own_capabilities"] = o.OwnCapabilities

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetCallResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"call",
		"duration",
		"members",
		"own_capabilities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetCallResponse := _GetCallResponse{}

	err = json.Unmarshal(data, &varGetCallResponse)

	if err != nil {
		return err
	}

	*o = GetCallResponse(varGetCallResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "call")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "members")
		delete(additionalProperties, "membership")
		delete(additionalProperties, "own_capabilities")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetCallResponse struct {
	value *GetCallResponse
	isSet bool
}

func (v NullableGetCallResponse) Get() *GetCallResponse {
	return v.value
}

func (v *NullableGetCallResponse) Set(val *GetCallResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCallResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCallResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCallResponse(val *GetCallResponse) *NullableGetCallResponse {
	return &NullableGetCallResponse{value: val, isSet: true}
}

func (v NullableGetCallResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCallResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


