/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the QueryMembersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryMembersResponse{}

// QueryMembersResponse struct for QueryMembersResponse
type QueryMembersResponse struct {
	// Duration of the request in human-readable format
	Duration string `json:"duration"`
	Members []MemberResponse `json:"members"`
	Next *string `json:"next,omitempty"`
	Prev *string `json:"prev,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _QueryMembersResponse QueryMembersResponse

// NewQueryMembersResponse instantiates a new QueryMembersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryMembersResponse(duration string, members []MemberResponse) *QueryMembersResponse {
	this := QueryMembersResponse{}
	this.Duration = duration
	this.Members = members
	return &this
}

// NewQueryMembersResponseWithDefaults instantiates a new QueryMembersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryMembersResponseWithDefaults() *QueryMembersResponse {
	this := QueryMembersResponse{}
	return &this
}

// GetDuration returns the Duration field value
func (o *QueryMembersResponse) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *QueryMembersResponse) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *QueryMembersResponse) SetDuration(v string) {
	o.Duration = v
}

// GetMembers returns the Members field value
func (o *QueryMembersResponse) GetMembers() []MemberResponse {
	if o == nil {
		var ret []MemberResponse
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *QueryMembersResponse) GetMembersOk() ([]MemberResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *QueryMembersResponse) SetMembers(v []MemberResponse) {
	o.Members = v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *QueryMembersResponse) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryMembersResponse) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *QueryMembersResponse) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *QueryMembersResponse) SetNext(v string) {
	o.Next = &v
}

// GetPrev returns the Prev field value if set, zero value otherwise.
func (o *QueryMembersResponse) GetPrev() string {
	if o == nil || IsNil(o.Prev) {
		var ret string
		return ret
	}
	return *o.Prev
}

// GetPrevOk returns a tuple with the Prev field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryMembersResponse) GetPrevOk() (*string, bool) {
	if o == nil || IsNil(o.Prev) {
		return nil, false
	}
	return o.Prev, true
}

// HasPrev returns a boolean if a field has been set.
func (o *QueryMembersResponse) HasPrev() bool {
	if o != nil && !IsNil(o.Prev) {
		return true
	}

	return false
}

// SetPrev gets a reference to the given string and assigns it to the Prev field.
func (o *QueryMembersResponse) SetPrev(v string) {
	o.Prev = &v
}

func (o QueryMembersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryMembersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration
	toSerialize["members"] = o.Members
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Prev) {
		toSerialize["prev"] = o.Prev
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QueryMembersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration",
		"members",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryMembersResponse := _QueryMembersResponse{}

	err = json.Unmarshal(data, &varQueryMembersResponse)

	if err != nil {
		return err
	}

	*o = QueryMembersResponse(varQueryMembersResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "duration")
		delete(additionalProperties, "members")
		delete(additionalProperties, "next")
		delete(additionalProperties, "prev")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQueryMembersResponse struct {
	value *QueryMembersResponse
	isSet bool
}

func (v NullableQueryMembersResponse) Get() *QueryMembersResponse {
	return v.value
}

func (v *NullableQueryMembersResponse) Set(val *QueryMembersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryMembersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryMembersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryMembersResponse(val *QueryMembersResponse) *NullableQueryMembersResponse {
	return &NullableQueryMembersResponse{value: val, isSet: true}
}

func (v NullableQueryMembersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryMembersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


