/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
)

// checks if the GeofenceSettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeofenceSettingsRequest{}

// GeofenceSettingsRequest struct for GeofenceSettingsRequest
type GeofenceSettingsRequest struct {
	Names []string `json:"names,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GeofenceSettingsRequest GeofenceSettingsRequest

// NewGeofenceSettingsRequest instantiates a new GeofenceSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeofenceSettingsRequest() *GeofenceSettingsRequest {
	this := GeofenceSettingsRequest{}
	return &this
}

// NewGeofenceSettingsRequestWithDefaults instantiates a new GeofenceSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeofenceSettingsRequestWithDefaults() *GeofenceSettingsRequest {
	this := GeofenceSettingsRequest{}
	return &this
}

// GetNames returns the Names field value if set, zero value otherwise.
func (o *GeofenceSettingsRequest) GetNames() []string {
	if o == nil || IsNil(o.Names) {
		var ret []string
		return ret
	}
	return o.Names
}

// GetNamesOk returns a tuple with the Names field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeofenceSettingsRequest) GetNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.Names) {
		return nil, false
	}
	return o.Names, true
}

// HasNames returns a boolean if a field has been set.
func (o *GeofenceSettingsRequest) HasNames() bool {
	if o != nil && !IsNil(o.Names) {
		return true
	}

	return false
}

// SetNames gets a reference to the given []string and assigns it to the Names field.
func (o *GeofenceSettingsRequest) SetNames(v []string) {
	o.Names = v
}

func (o GeofenceSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeofenceSettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Names) {
		toSerialize["names"] = o.Names
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GeofenceSettingsRequest) UnmarshalJSON(data []byte) (err error) {
	varGeofenceSettingsRequest := _GeofenceSettingsRequest{}

	err = json.Unmarshal(data, &varGeofenceSettingsRequest)

	if err != nil {
		return err
	}

	*o = GeofenceSettingsRequest(varGeofenceSettingsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "names")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGeofenceSettingsRequest struct {
	value *GeofenceSettingsRequest
	isSet bool
}

func (v NullableGeofenceSettingsRequest) Get() *GeofenceSettingsRequest {
	return v.value
}

func (v *NullableGeofenceSettingsRequest) Set(val *GeofenceSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGeofenceSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGeofenceSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeofenceSettingsRequest(val *GeofenceSettingsRequest) *NullableGeofenceSettingsRequest {
	return &NullableGeofenceSettingsRequest{value: val, isSet: true}
}

func (v NullableGeofenceSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeofenceSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


