/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the UnblockUserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnblockUserRequest{}

// UnblockUserRequest struct for UnblockUserRequest
type UnblockUserRequest struct {
	// the user to unblock
	UserId string `json:"user_id"`
	AdditionalProperties map[string]interface{}
}

type _UnblockUserRequest UnblockUserRequest

// NewUnblockUserRequest instantiates a new UnblockUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnblockUserRequest(userId string) *UnblockUserRequest {
	this := UnblockUserRequest{}
	this.UserId = userId
	return &this
}

// NewUnblockUserRequestWithDefaults instantiates a new UnblockUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnblockUserRequestWithDefaults() *UnblockUserRequest {
	this := UnblockUserRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *UnblockUserRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UnblockUserRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UnblockUserRequest) SetUserId(v string) {
	o.UserId = v
}

func (o UnblockUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnblockUserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UnblockUserRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnblockUserRequest := _UnblockUserRequest{}

	err = json.Unmarshal(data, &varUnblockUserRequest)

	if err != nil {
		return err
	}

	*o = UnblockUserRequest(varUnblockUserRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUnblockUserRequest struct {
	value *UnblockUserRequest
	isSet bool
}

func (v NullableUnblockUserRequest) Get() *UnblockUserRequest {
	return v.value
}

func (v *NullableUnblockUserRequest) Set(val *UnblockUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnblockUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnblockUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnblockUserRequest(val *UnblockUserRequest) *NullableUnblockUserRequest {
	return &NullableUnblockUserRequest{value: val, isSet: true}
}

func (v NullableUnblockUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnblockUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


