/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the RecordSettingsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecordSettingsResponse{}

// RecordSettingsResponse struct for RecordSettingsResponse
type RecordSettingsResponse struct {
	AudioOnly bool `json:"audio_only"`
	Layout LayoutSettings `json:"layout"`
	Mode string `json:"mode"`
	Quality string `json:"quality"`
	AdditionalProperties map[string]interface{}
}

type _RecordSettingsResponse RecordSettingsResponse

// NewRecordSettingsResponse instantiates a new RecordSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecordSettingsResponse(audioOnly bool, layout LayoutSettings, mode string, quality string) *RecordSettingsResponse {
	this := RecordSettingsResponse{}
	this.AudioOnly = audioOnly
	this.Layout = layout
	this.Mode = mode
	this.Quality = quality
	return &this
}

// NewRecordSettingsResponseWithDefaults instantiates a new RecordSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecordSettingsResponseWithDefaults() *RecordSettingsResponse {
	this := RecordSettingsResponse{}
	return &this
}

// GetAudioOnly returns the AudioOnly field value
func (o *RecordSettingsResponse) GetAudioOnly() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AudioOnly
}

// GetAudioOnlyOk returns a tuple with the AudioOnly field value
// and a boolean to check if the value has been set.
func (o *RecordSettingsResponse) GetAudioOnlyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AudioOnly, true
}

// SetAudioOnly sets field value
func (o *RecordSettingsResponse) SetAudioOnly(v bool) {
	o.AudioOnly = v
}

// GetLayout returns the Layout field value
func (o *RecordSettingsResponse) GetLayout() LayoutSettings {
	if o == nil {
		var ret LayoutSettings
		return ret
	}

	return o.Layout
}

// GetLayoutOk returns a tuple with the Layout field value
// and a boolean to check if the value has been set.
func (o *RecordSettingsResponse) GetLayoutOk() (*LayoutSettings, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Layout, true
}

// SetLayout sets field value
func (o *RecordSettingsResponse) SetLayout(v LayoutSettings) {
	o.Layout = v
}

// GetMode returns the Mode field value
func (o *RecordSettingsResponse) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *RecordSettingsResponse) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *RecordSettingsResponse) SetMode(v string) {
	o.Mode = v
}

// GetQuality returns the Quality field value
func (o *RecordSettingsResponse) GetQuality() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quality
}

// GetQualityOk returns a tuple with the Quality field value
// and a boolean to check if the value has been set.
func (o *RecordSettingsResponse) GetQualityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quality, true
}

// SetQuality sets field value
func (o *RecordSettingsResponse) SetQuality(v string) {
	o.Quality = v
}

func (o RecordSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecordSettingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audio_only"] = o.AudioOnly
	toSerialize["layout"] = o.Layout
	toSerialize["mode"] = o.Mode
	toSerialize["quality"] = o.Quality

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RecordSettingsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"audio_only",
		"layout",
		"mode",
		"quality",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecordSettingsResponse := _RecordSettingsResponse{}

	err = json.Unmarshal(data, &varRecordSettingsResponse)

	if err != nil {
		return err
	}

	*o = RecordSettingsResponse(varRecordSettingsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "audio_only")
		delete(additionalProperties, "layout")
		delete(additionalProperties, "mode")
		delete(additionalProperties, "quality")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRecordSettingsResponse struct {
	value *RecordSettingsResponse
	isSet bool
}

func (v NullableRecordSettingsResponse) Get() *RecordSettingsResponse {
	return v.value
}

func (v *NullableRecordSettingsResponse) Set(val *RecordSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordSettingsResponse(val *RecordSettingsResponse) *NullableRecordSettingsResponse {
	return &NullableRecordSettingsResponse{value: val, isSet: true}
}

func (v NullableRecordSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


