/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the TargetResolution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TargetResolution{}

// TargetResolution struct for TargetResolution
type TargetResolution struct {
	Bitrate int32 `json:"bitrate"`
	Height int32 `json:"height"`
	Width int32 `json:"width"`
	AdditionalProperties map[string]interface{}
}

type _TargetResolution TargetResolution

// NewTargetResolution instantiates a new TargetResolution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTargetResolution(bitrate int32, height int32, width int32) *TargetResolution {
	this := TargetResolution{}
	this.Bitrate = bitrate
	this.Height = height
	this.Width = width
	return &this
}

// NewTargetResolutionWithDefaults instantiates a new TargetResolution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTargetResolutionWithDefaults() *TargetResolution {
	this := TargetResolution{}
	return &this
}

// GetBitrate returns the Bitrate field value
func (o *TargetResolution) GetBitrate() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Bitrate
}

// GetBitrateOk returns a tuple with the Bitrate field value
// and a boolean to check if the value has been set.
func (o *TargetResolution) GetBitrateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bitrate, true
}

// SetBitrate sets field value
func (o *TargetResolution) SetBitrate(v int32) {
	o.Bitrate = v
}

// GetHeight returns the Height field value
func (o *TargetResolution) GetHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *TargetResolution) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *TargetResolution) SetHeight(v int32) {
	o.Height = v
}

// GetWidth returns the Width field value
func (o *TargetResolution) GetWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *TargetResolution) GetWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *TargetResolution) SetWidth(v int32) {
	o.Width = v
}

func (o TargetResolution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TargetResolution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bitrate"] = o.Bitrate
	toSerialize["height"] = o.Height
	toSerialize["width"] = o.Width

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TargetResolution) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bitrate",
		"height",
		"width",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTargetResolution := _TargetResolution{}

	err = json.Unmarshal(data, &varTargetResolution)

	if err != nil {
		return err
	}

	*o = TargetResolution(varTargetResolution)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bitrate")
		delete(additionalProperties, "height")
		delete(additionalProperties, "width")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTargetResolution struct {
	value *TargetResolution
	isSet bool
}

func (v NullableTargetResolution) Get() *TargetResolution {
	return v.value
}

func (v *NullableTargetResolution) Set(val *TargetResolution) {
	v.value = val
	v.isSet = true
}

func (v NullableTargetResolution) IsSet() bool {
	return v.isSet
}

func (v *NullableTargetResolution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTargetResolution(val *TargetResolution) *NullableTargetResolution {
	return &NullableTargetResolution{value: val, isSet: true}
}

func (v NullableTargetResolution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTargetResolution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


