/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
)

// checks if the SortParamRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SortParamRequest{}

// SortParamRequest struct for SortParamRequest
type SortParamRequest struct {
	// Direction of sorting, -1 for descending, 1 for ascending
	Direction *int32 `json:"direction,omitempty"`
	// Name of field to sort by
	Field *string `json:"field,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SortParamRequest SortParamRequest

// NewSortParamRequest instantiates a new SortParamRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSortParamRequest() *SortParamRequest {
	this := SortParamRequest{}
	return &this
}

// NewSortParamRequestWithDefaults instantiates a new SortParamRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSortParamRequestWithDefaults() *SortParamRequest {
	this := SortParamRequest{}
	return &this
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *SortParamRequest) GetDirection() int32 {
	if o == nil || IsNil(o.Direction) {
		var ret int32
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SortParamRequest) GetDirectionOk() (*int32, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *SortParamRequest) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given int32 and assigns it to the Direction field.
func (o *SortParamRequest) SetDirection(v int32) {
	o.Direction = &v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *SortParamRequest) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SortParamRequest) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *SortParamRequest) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *SortParamRequest) SetField(v string) {
	o.Field = &v
}

func (o SortParamRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SortParamRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SortParamRequest) UnmarshalJSON(data []byte) (err error) {
	varSortParamRequest := _SortParamRequest{}

	err = json.Unmarshal(data, &varSortParamRequest)

	if err != nil {
		return err
	}

	*o = SortParamRequest(varSortParamRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "direction")
		delete(additionalProperties, "field")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSortParamRequest struct {
	value *SortParamRequest
	isSet bool
}

func (v NullableSortParamRequest) Get() *SortParamRequest {
	return v.value
}

func (v *NullableSortParamRequest) Set(val *SortParamRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSortParamRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSortParamRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSortParamRequest(val *SortParamRequest) *NullableSortParamRequest {
	return &NullableSortParamRequest{value: val, isSet: true}
}

func (v NullableSortParamRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSortParamRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


