/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateGuestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateGuestResponse{}

// CreateGuestResponse struct for CreateGuestResponse
type CreateGuestResponse struct {
	// the access token to authenticate the user
	AccessToken string `json:"access_token"`
	Duration string `json:"duration"`
	User UserResponse `json:"user"`
	AdditionalProperties map[string]interface{}
}

type _CreateGuestResponse CreateGuestResponse

// NewCreateGuestResponse instantiates a new CreateGuestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGuestResponse(accessToken string, duration string, user UserResponse) *CreateGuestResponse {
	this := CreateGuestResponse{}
	this.AccessToken = accessToken
	this.Duration = duration
	this.User = user
	return &this
}

// NewCreateGuestResponseWithDefaults instantiates a new CreateGuestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGuestResponseWithDefaults() *CreateGuestResponse {
	this := CreateGuestResponse{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *CreateGuestResponse) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *CreateGuestResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *CreateGuestResponse) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetDuration returns the Duration field value
func (o *CreateGuestResponse) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *CreateGuestResponse) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *CreateGuestResponse) SetDuration(v string) {
	o.Duration = v
}

// GetUser returns the User field value
func (o *CreateGuestResponse) GetUser() UserResponse {
	if o == nil {
		var ret UserResponse
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *CreateGuestResponse) GetUserOk() (*UserResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *CreateGuestResponse) SetUser(v UserResponse) {
	o.User = v
}

func (o CreateGuestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGuestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["duration"] = o.Duration
	toSerialize["user"] = o.User

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateGuestResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"duration",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateGuestResponse := _CreateGuestResponse{}

	err = json.Unmarshal(data, &varCreateGuestResponse)

	if err != nil {
		return err
	}

	*o = CreateGuestResponse(varCreateGuestResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "access_token")
		delete(additionalProperties, "duration")
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateGuestResponse struct {
	value *CreateGuestResponse
	isSet bool
}

func (v NullableCreateGuestResponse) Get() *CreateGuestResponse {
	return v.value
}

func (v *NullableCreateGuestResponse) Set(val *CreateGuestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGuestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGuestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGuestResponse(val *CreateGuestResponse) *NullableCreateGuestResponse {
	return &NullableCreateGuestResponse{value: val, isSet: true}
}

func (v NullableCreateGuestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGuestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


