/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
)

// checks if the SendEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendEventRequest{}

// SendEventRequest struct for SendEventRequest
type SendEventRequest struct {
	Custom map[string]interface{} `json:"custom,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SendEventRequest SendEventRequest

// NewSendEventRequest instantiates a new SendEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendEventRequest() *SendEventRequest {
	this := SendEventRequest{}
	return &this
}

// NewSendEventRequestWithDefaults instantiates a new SendEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendEventRequestWithDefaults() *SendEventRequest {
	this := SendEventRequest{}
	return &this
}

// GetCustom returns the Custom field value if set, zero value otherwise.
func (o *SendEventRequest) GetCustom() map[string]interface{} {
	if o == nil || IsNil(o.Custom) {
		var ret map[string]interface{}
		return ret
	}
	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEventRequest) GetCustomOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Custom) {
		return map[string]interface{}{}, false
	}
	return o.Custom, true
}

// HasCustom returns a boolean if a field has been set.
func (o *SendEventRequest) HasCustom() bool {
	if o != nil && !IsNil(o.Custom) {
		return true
	}

	return false
}

// SetCustom gets a reference to the given map[string]interface{} and assigns it to the Custom field.
func (o *SendEventRequest) SetCustom(v map[string]interface{}) {
	o.Custom = v
}

func (o SendEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Custom) {
		toSerialize["custom"] = o.Custom
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SendEventRequest) UnmarshalJSON(data []byte) (err error) {
	varSendEventRequest := _SendEventRequest{}

	err = json.Unmarshal(data, &varSendEventRequest)

	if err != nil {
		return err
	}

	*o = SendEventRequest(varSendEventRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "custom")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSendEventRequest struct {
	value *SendEventRequest
	isSet bool
}

func (v NullableSendEventRequest) Get() *SendEventRequest {
	return v.value
}

func (v *NullableSendEventRequest) Set(val *SendEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendEventRequest(val *SendEventRequest) *NullableSendEventRequest {
	return &NullableSendEventRequest{value: val, isSet: true}
}

func (v NullableSendEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


