/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the ListTranscriptionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTranscriptionsResponse{}

// ListTranscriptionsResponse struct for ListTranscriptionsResponse
type ListTranscriptionsResponse struct {
	Duration string `json:"duration"`
	Transcriptions []CallTranscription `json:"transcriptions"`
	AdditionalProperties map[string]interface{}
}

type _ListTranscriptionsResponse ListTranscriptionsResponse

// NewListTranscriptionsResponse instantiates a new ListTranscriptionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTranscriptionsResponse(duration string, transcriptions []CallTranscription) *ListTranscriptionsResponse {
	this := ListTranscriptionsResponse{}
	this.Duration = duration
	this.Transcriptions = transcriptions
	return &this
}

// NewListTranscriptionsResponseWithDefaults instantiates a new ListTranscriptionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTranscriptionsResponseWithDefaults() *ListTranscriptionsResponse {
	this := ListTranscriptionsResponse{}
	return &this
}

// GetDuration returns the Duration field value
func (o *ListTranscriptionsResponse) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *ListTranscriptionsResponse) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *ListTranscriptionsResponse) SetDuration(v string) {
	o.Duration = v
}

// GetTranscriptions returns the Transcriptions field value
func (o *ListTranscriptionsResponse) GetTranscriptions() []CallTranscription {
	if o == nil {
		var ret []CallTranscription
		return ret
	}

	return o.Transcriptions
}

// GetTranscriptionsOk returns a tuple with the Transcriptions field value
// and a boolean to check if the value has been set.
func (o *ListTranscriptionsResponse) GetTranscriptionsOk() ([]CallTranscription, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transcriptions, true
}

// SetTranscriptions sets field value
func (o *ListTranscriptionsResponse) SetTranscriptions(v []CallTranscription) {
	o.Transcriptions = v
}

func (o ListTranscriptionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTranscriptionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration
	toSerialize["transcriptions"] = o.Transcriptions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListTranscriptionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration",
		"transcriptions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListTranscriptionsResponse := _ListTranscriptionsResponse{}

	err = json.Unmarshal(data, &varListTranscriptionsResponse)

	if err != nil {
		return err
	}

	*o = ListTranscriptionsResponse(varListTranscriptionsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "duration")
		delete(additionalProperties, "transcriptions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListTranscriptionsResponse struct {
	value *ListTranscriptionsResponse
	isSet bool
}

func (v NullableListTranscriptionsResponse) Get() *ListTranscriptionsResponse {
	return v.value
}

func (v *NullableListTranscriptionsResponse) Set(val *ListTranscriptionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListTranscriptionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListTranscriptionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTranscriptionsResponse(val *ListTranscriptionsResponse) *NullableListTranscriptionsResponse {
	return &NullableListTranscriptionsResponse{value: val, isSet: true}
}

func (v NullableListTranscriptionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTranscriptionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


