/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the BroadcastSettingsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BroadcastSettingsResponse{}

// BroadcastSettingsResponse struct for BroadcastSettingsResponse
type BroadcastSettingsResponse struct {
	Enabled bool `json:"enabled"`
	Hls HLSSettingsResponse `json:"hls"`
	AdditionalProperties map[string]interface{}
}

type _BroadcastSettingsResponse BroadcastSettingsResponse

// NewBroadcastSettingsResponse instantiates a new BroadcastSettingsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBroadcastSettingsResponse(enabled bool, hls HLSSettingsResponse) *BroadcastSettingsResponse {
	this := BroadcastSettingsResponse{}
	this.Enabled = enabled
	this.Hls = hls
	return &this
}

// NewBroadcastSettingsResponseWithDefaults instantiates a new BroadcastSettingsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBroadcastSettingsResponseWithDefaults() *BroadcastSettingsResponse {
	this := BroadcastSettingsResponse{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *BroadcastSettingsResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *BroadcastSettingsResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *BroadcastSettingsResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetHls returns the Hls field value
func (o *BroadcastSettingsResponse) GetHls() HLSSettingsResponse {
	if o == nil {
		var ret HLSSettingsResponse
		return ret
	}

	return o.Hls
}

// GetHlsOk returns a tuple with the Hls field value
// and a boolean to check if the value has been set.
func (o *BroadcastSettingsResponse) GetHlsOk() (*HLSSettingsResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hls, true
}

// SetHls sets field value
func (o *BroadcastSettingsResponse) SetHls(v HLSSettingsResponse) {
	o.Hls = v
}

func (o BroadcastSettingsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BroadcastSettingsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["hls"] = o.Hls

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BroadcastSettingsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"hls",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBroadcastSettingsResponse := _BroadcastSettingsResponse{}

	err = json.Unmarshal(data, &varBroadcastSettingsResponse)

	if err != nil {
		return err
	}

	*o = BroadcastSettingsResponse(varBroadcastSettingsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "hls")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBroadcastSettingsResponse struct {
	value *BroadcastSettingsResponse
	isSet bool
}

func (v NullableBroadcastSettingsResponse) Get() *BroadcastSettingsResponse {
	return v.value
}

func (v *NullableBroadcastSettingsResponse) Set(val *BroadcastSettingsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBroadcastSettingsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBroadcastSettingsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBroadcastSettingsResponse(val *BroadcastSettingsResponse) *NullableBroadcastSettingsResponse {
	return &NullableBroadcastSettingsResponse{value: val, isSet: true}
}

func (v NullableBroadcastSettingsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBroadcastSettingsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


