/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the ExternalStorageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalStorageResponse{}

// ExternalStorageResponse struct for ExternalStorageResponse
type ExternalStorageResponse struct {
	Bucket string `json:"bucket"`
	Name string `json:"name"`
	Path string `json:"path"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _ExternalStorageResponse ExternalStorageResponse

// NewExternalStorageResponse instantiates a new ExternalStorageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalStorageResponse(bucket string, name string, path string, type_ string) *ExternalStorageResponse {
	this := ExternalStorageResponse{}
	this.Bucket = bucket
	this.Name = name
	this.Path = path
	this.Type = type_
	return &this
}

// NewExternalStorageResponseWithDefaults instantiates a new ExternalStorageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalStorageResponseWithDefaults() *ExternalStorageResponse {
	this := ExternalStorageResponse{}
	return &this
}

// GetBucket returns the Bucket field value
func (o *ExternalStorageResponse) GetBucket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value
// and a boolean to check if the value has been set.
func (o *ExternalStorageResponse) GetBucketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bucket, true
}

// SetBucket sets field value
func (o *ExternalStorageResponse) SetBucket(v string) {
	o.Bucket = v
}

// GetName returns the Name field value
func (o *ExternalStorageResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ExternalStorageResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ExternalStorageResponse) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *ExternalStorageResponse) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ExternalStorageResponse) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ExternalStorageResponse) SetPath(v string) {
	o.Path = v
}

// GetType returns the Type field value
func (o *ExternalStorageResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ExternalStorageResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ExternalStorageResponse) SetType(v string) {
	o.Type = v
}

func (o ExternalStorageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalStorageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bucket"] = o.Bucket
	toSerialize["name"] = o.Name
	toSerialize["path"] = o.Path
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExternalStorageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bucket",
		"name",
		"path",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExternalStorageResponse := _ExternalStorageResponse{}

	err = json.Unmarshal(data, &varExternalStorageResponse)

	if err != nil {
		return err
	}

	*o = ExternalStorageResponse(varExternalStorageResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bucket")
		delete(additionalProperties, "name")
		delete(additionalProperties, "path")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExternalStorageResponse struct {
	value *ExternalStorageResponse
	isSet bool
}

func (v NullableExternalStorageResponse) Get() *ExternalStorageResponse {
	return v.value
}

func (v *NullableExternalStorageResponse) Set(val *ExternalStorageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalStorageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalStorageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalStorageResponse(val *ExternalStorageResponse) *NullableExternalStorageResponse {
	return &NullableExternalStorageResponse{value: val, isSet: true}
}

func (v NullableExternalStorageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalStorageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


