/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the UnpinResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnpinResponse{}

// UnpinResponse struct for UnpinResponse
type UnpinResponse struct {
	// Duration of the request in human-readable format
	Duration string `json:"duration"`
	AdditionalProperties map[string]interface{}
}

type _UnpinResponse UnpinResponse

// NewUnpinResponse instantiates a new UnpinResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnpinResponse(duration string) *UnpinResponse {
	this := UnpinResponse{}
	this.Duration = duration
	return &this
}

// NewUnpinResponseWithDefaults instantiates a new UnpinResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnpinResponseWithDefaults() *UnpinResponse {
	this := UnpinResponse{}
	return &this
}

// GetDuration returns the Duration field value
func (o *UnpinResponse) GetDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *UnpinResponse) GetDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *UnpinResponse) SetDuration(v string) {
	o.Duration = v
}

func (o UnpinResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnpinResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UnpinResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnpinResponse := _UnpinResponse{}

	err = json.Unmarshal(data, &varUnpinResponse)

	if err != nil {
		return err
	}

	*o = UnpinResponse(varUnpinResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "duration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUnpinResponse struct {
	value *UnpinResponse
	isSet bool
}

func (v NullableUnpinResponse) Get() *UnpinResponse {
	return v.value
}

func (v *NullableUnpinResponse) Set(val *UnpinResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUnpinResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUnpinResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnpinResponse(val *UnpinResponse) *NullableUnpinResponse {
	return &NullableUnpinResponse{value: val, isSet: true}
}

func (v NullableUnpinResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnpinResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


