/*
Stream API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v100.14.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package getstream_video

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateGuestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateGuestRequest{}

// CreateGuestRequest struct for CreateGuestRequest
type CreateGuestRequest struct {
	User UserRequest `json:"user"`
	AdditionalProperties map[string]interface{}
}

type _CreateGuestRequest CreateGuestRequest

// NewCreateGuestRequest instantiates a new CreateGuestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGuestRequest(user UserRequest) *CreateGuestRequest {
	this := CreateGuestRequest{}
	this.User = user
	return &this
}

// NewCreateGuestRequestWithDefaults instantiates a new CreateGuestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGuestRequestWithDefaults() *CreateGuestRequest {
	this := CreateGuestRequest{}
	return &this
}

// GetUser returns the User field value
func (o *CreateGuestRequest) GetUser() UserRequest {
	if o == nil {
		var ret UserRequest
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *CreateGuestRequest) GetUserOk() (*UserRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *CreateGuestRequest) SetUser(v UserRequest) {
	o.User = v
}

func (o CreateGuestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGuestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user"] = o.User

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateGuestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateGuestRequest := _CreateGuestRequest{}

	err = json.Unmarshal(data, &varCreateGuestRequest)

	if err != nil {
		return err
	}

	*o = CreateGuestRequest(varCreateGuestRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateGuestRequest struct {
	value *CreateGuestRequest
	isSet bool
}

func (v NullableCreateGuestRequest) Get() *CreateGuestRequest {
	return v.value
}

func (v *NullableCreateGuestRequest) Set(val *CreateGuestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGuestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGuestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGuestRequest(val *CreateGuestRequest) *NullableCreateGuestRequest {
	return &NullableCreateGuestRequest{value: val, isSet: true}
}

func (v NullableCreateGuestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGuestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


